
const frontendConfig = {
    CLOUDINARY_CLOUD_NAME:import.meta.env.VITE_CLOUDINARY_CLOUD_NAME,
    BACKEND_URL:import.meta.env.VITE_BACKEND_URL,
    FRONTEND_URL:import.meta.env.VITE_FRONTEND_URL,
    POST_SOCKET_URL:import.meta.env.VITE_POST_SOCKET_URL,
    POST_HANDSHAKE_PATH:import.meta.env.VITE_POST_HANDSHAKE_PATH,
    FOLLOW_SOCKET_URL:import.meta.env.VITE_FOLLOW_SOCKET_URL,
    FOLLOW_HANDSHAKE_PATH:import.meta.env.VITE_FOLLOW_HANDSHAKE_PATH,
    LIKE_SOCKET_URL:import.meta.env.VITE_LIKE_SOCKET_URL,
    LIKE_HANDSHAKE_PATH:import.meta.env.VITE_LIKE_HANDSHAKE_PATH,
    COMMENT_SOCKET_URL:import.meta.env.VITE_COMMENT_SOCKET_URL,
    COMMENT_HANDSHAKE_PATH:import.meta.env.VITE_COMMENT_HANDSHAKE_PATH,
    NOTIFICATION_SOCKET_URL:import.meta.env.VITE_NOTIFICATION_SOCKET_URL,
    NOTIFICATION_HANDSHAKE_PATH:import.meta.env.VITE_NOTIFICATION_HANDSHAKE_PATH,
    VIEWS_SOCKET_URL:import.meta.env.VITE_VIEWS_SOCKET_URL,
    VIEWS_HANDSHAKE_PATH:import.meta.env.VITE_VIEWS_HANDSHAKE_PATH,
    USER_SOCKET_URL:import.meta.env.VITE_USER_SOCKET_URL,
    USER_HANDSHAKE_PATH:import.meta.env.VITE_USER_HANDSHAKE_PATH,
}

export default frontendConfig;